name: Security Check Workflow

on:
  push:
    branches:
      - main

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start security check
      id: start-check
      run: |
        CHECK_RESPONSE=$(curl -s -X POST "http://poccallwebsocketsapi-9ef338a96eff.herokuapp.com/start-check")
        echo "Response: $CHECK_RESPONSE"
        echo "CHECK_ID=$(echo $CHECK_RESPONSE | tr -d '\"')" >> $GITHUB_ENV

    - name: Install websocket-client
      run: pip install websocket-client

    - name: Create WebSocket client script
      run: |
        cat << EOF > ws_client.py
        import websocket
        import sys

        def on_message(ws, message):
            print(f"Received message: {message}")
            if message == "approved":
                sys.exit(0)
            else:
                sys.exit(1)

        def on_error(ws, error):
            print(f"Error: {error}")
            if error == 0:
              sys.exit(0)
            else:
              sys.exit(1)

        def on_close(ws, close_status_code, close_msg):
            print("Connection closed")

        def main():
            check_id = sys.argv[1]
            ws_url = f"ws://poccallwebsocketsapi-9ef338a96eff.herokuapp.com/ws/{check_id}"
            ws = websocket.WebSocketApp(ws_url,
                                        on_message=on_message,
                                        on_error=on_error,
                                        on_close=on_close)
            ws.run_forever()

        if __name__ == "__main__":
            main()
        EOF

    - name: Wait for security check result via WebSocket
      run: python ws_client.py $CHECK_ID
